-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('PlayerInfo_pb')


local PLAYERINFO = protobuf.Descriptor();
local PLAYERINFO_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_NAME_FIELD = protobuf.FieldDescriptor();

PLAYERINFO_ID_FIELD.name = "id"
PLAYERINFO_ID_FIELD.full_name = ".PlayerInfo.id"
PLAYERINFO_ID_FIELD.number = 1
PLAYERINFO_ID_FIELD.index = 0
PLAYERINFO_ID_FIELD.label = 1
PLAYERINFO_ID_FIELD.has_default_value = false
PLAYERINFO_ID_FIELD.default_value = 0
PLAYERINFO_ID_FIELD.type = 5
PLAYERINFO_ID_FIELD.cpp_type = 1

PLAYERINFO_NAME_FIELD.name = "name"
PLAYERINFO_NAME_FIELD.full_name = ".PlayerInfo.name"
PLAYERINFO_NAME_FIELD.number = 2
PLAYERINFO_NAME_FIELD.index = 1
PLAYERINFO_NAME_FIELD.label = 1
PLAYERINFO_NAME_FIELD.has_default_value = false
PLAYERINFO_NAME_FIELD.default_value = ""
PLAYERINFO_NAME_FIELD.type = 9
PLAYERINFO_NAME_FIELD.cpp_type = 9

PLAYERINFO.name = "PlayerInfo"
PLAYERINFO.full_name = ".PlayerInfo"
PLAYERINFO.nested_types = {}
PLAYERINFO.enum_types = {}
PLAYERINFO.fields = {PLAYERINFO_ID_FIELD, PLAYERINFO_NAME_FIELD}
PLAYERINFO.is_extendable = false
PLAYERINFO.extensions = {}

PlayerInfo = protobuf.Message(PLAYERINFO)

